### ISSUE TITLE
JSON malformed

### ISSUE THREAD

**Issue by stezarpriansya** [alhasinun/API-IHSAN#1]
Hi Ihsan, this is a nice API, good job!

Actually, creating a JSON result on FastAPI is easy, you just need to return a dictionary variable, and automatically will convert to JSON without any effort. Please take a look to your code for this, you don't need to do JSON.dumps() method, because it will returned like this, JSON cannot well formated.
![image](https://user-images.githubusercontent.com/7480754/116831293-8950ed80-abd8-11eb-9b67-f045c1995ee3.png)

Also, the second feedback is add more sorting values if you have same rating (e.g. rating count, etc.). It will be more objective since you have 2 criteria to sorting your data.
![image](https://user-images.githubusercontent.com/7480754/116831371-15631500-abd9-11eb-876d-509e04c47d45.png)

Thanks.

**Comment by alhasinun** [comment]
Hi Stezar,

Thank you for your feedback. I already changed my final output code (for displaying JSON), and it works. 
I really appreciate your feedback because this topic is really new to me and I still need some learning.

**Comment by stezarpriansya** [comment]
> Hi Stezar,
> 
> Thank you for your feedback. I already changed my final output code (for displaying JSON), and it works. 
> I really appreciate your feedback because this topic is really new to me and I still need some learning.

Cool, nice to hear that. It's OK, keep learn & practice ya!
